### ISSUE TITLE
Поменять пример использования

### ISSUE THREAD

**Issue by magstrong07** [AdmiralDS/icons#27]
На данный момент пример использования копируется в таком виде:
 import { ReactComponent as AcceptSolid } from '@admiral-ds/icons/build/category/AcceptSolid.svg';
 
Сейчас есть три варианта, который можно использовать. Необходимо актуализировать примеры

```
 Импорт оптимизированной иконки через настроенный SVGR лоадер (https://react-svgr.com/docs/what-is-svgr/)
import ArrowRightOutline from '@admiral-ds/icons/build/category/CreatePullRequestSolid.svg?react';

 Импорт оригинала иконки через настроенный SVGR лоадер (https://react-svgr.com/docs/what-is-svgr/)
import BusSolid from '@admiral-ds/icons/public/icons/category/Bus Solid.svg?react';

Импорт иконки как готового реакт компонента (лоадер не требуется)
import { CategoryBusOutline } from '@admiral-ds/icons';
```

**Comment by Parasjona** [comment]
Примеры в тексте сторибука (на главной): нужно описать все три варианта.
В копировании примера под каждой свг: как вариант сделать выпадашку, где можно выбрать один из трёх вариантов для копирования.
